<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewusers.aspx.cs" Inherits="WebApplication2.viewusers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel = "stylesheet" type = "text/css" href = "ss.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GV" AutoGenerateDeleteButton="true" OnRowDeleting="GV_RowDeleting" runat="server" ></asp:GridView>

        </div>
    </form>
</body>
</html>
